version: '3.9'
services:
  front:
    build:
      context: './react-docker'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    image: client:18.12.0-alpine
    networks:
      - mern-stack-network
    volumes:
      - ./react-docker:/app
    depends_on:
      - backend
  backend:
    build:
      context: './express-docker'
      dockerfile: Dockerfile
    image: server:18.12.0-alpine
    ports:
      - 5500:5500
    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./express-docker:/app
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - ./data/db:/data/db
networks:
  mern-stack-network:
# volumes:
#   mongoData:
